const shopLeftData = [
    {
        pic: "/assets/images/left1.png",
        title: "Dictum morbi",
        offerPrice: "$26.00",
        regularPrice: "$52.00",
        review: "/assets/images/reviews.png",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    },
    {
        pic: "/assets/images/left2.png",
        title: "Sodales sit",
        offerPrice: "$26.00",
        regularPrice: "$52.00",
        review: "/assets/images/reviews.png",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    },
    {
        pic: "/assets/images/left4.png",
        title: "Nibh varius",
        offerPrice: "$26.00",
        regularPrice: "$52.00",
        review: "/assets/images/reviews.png",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    },
    {
        pic: "/assets/images/left5.png",
        title: "Mauris quis",
        offerPrice: "$26.00",
        regularPrice: "$52.00",
        review: "/assets/images/reviews.png",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    },
    {
        pic: "/assets/images/left6.png",
        title: "Morbi sagittis",
        offerPrice: "$26.00",
        regularPrice: "$52.00",
        review: "/assets/images/reviews.png",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    },
    {
        pic: "/assets/images/left7.png",
        title: "Ultricies venenatis",
        offerPrice: "$26.00",
        regularPrice: "$52.00",
        review: "/assets/images/reviews.png",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    },
    {
        pic: "/assets/images/left8.png",
        title: "Scelerisque dignissim",
        offerPrice: "$26.00",
        regularPrice: "$52.00",
        review: "/assets/images/reviews.png",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    }, 
]

export default shopLeftData